INSERT_BATCH_SIZE = 1000
SQL_SELECT_LIMIT = 1000

DST_PORT_COL = 6
DST_PROTOCOL_COL = 7

TAG_OUTPUT_FILE = "flow_log_tag_insights.tsv"
PORT_PROTOCOL_FILE = "flow_log_port_protocol_insights.tsv"

DST_PORT_COL = 6
DST_PROTOCOL_COL = 7

TAG_HEADER = "Tag"
COUNT_HEADER = "Count"
PORT_HEADER = "Port"
PROTOCOL_HEADER = "Protocol"
